/**
 * Catálogo global de permissões do sistema.
 *
 * Espelha `PermissionCode` do backend
 * (`fluxa-backend/src/shared/constants/access-control.constant.ts`) e é usado
 * para filtrar itens da sidebar e telas. Nunca usar strings soltas.
 *
 * TODO: Revisar periodicamente contra o enum do backend (novas permissões).
 */
export enum PermissionCode {
  MANAGE_COMPANY = 'MANAGE_COMPANY',
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_VEHICLES = 'MANAGE_VEHICLES',
  MANAGE_VEHICLE_TYPES = 'MANAGE_VEHICLE_TYPES',
  MANAGE_DEPARTMENTS = 'MANAGE_DEPARTMENTS',
  MANAGE_ENTRANCES = 'MANAGE_ENTRANCES',
  MANAGE_BLOCKS = 'MANAGE_BLOCKS',
  MANAGE_ACCESS_REQUESTS = 'MANAGE_ACCESS_REQUESTS',
  MANAGE_BLOCK_REQUESTS = 'MANAGE_BLOCK_REQUESTS',
  MANAGE_IMPORTS = 'MANAGE_IMPORTS',
  MANAGE_DEVICES = 'MANAGE_DEVICES',
  GRANT_FREE_PASS = 'GRANT_FREE_PASS',
  PRINT_QRCODE = 'PRINT_QRCODE',
  VIEW_DASHBOARDS = 'VIEW_DASHBOARDS',
  REGISTER_ENTRY = 'REGISTER_ENTRY',
  REGISTER_EXIT = 'REGISTER_EXIT',
  REGISTER_DENIAL = 'REGISTER_DENIAL',
  CREATE_ACCESS_REQUEST = 'CREATE_ACCESS_REQUEST',
  CANCEL_ACCESS_REQUEST = 'CANCEL_ACCESS_REQUEST',
  CREATE_BLOCK_REQUEST = 'CREATE_BLOCK_REQUEST',
  MANUAL_CLOSE_ACCESS = 'MANUAL_CLOSE_ACCESS',
  INITIAL_ENTRY = 'INITIAL_ENTRY',
}
