/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateBlocksRouteImport } from './routes/_private/blocks'
import { Route as PrivateHomeRouteImport } from './routes/_private/home'
import { Route as PrivateOcupacaoRouteImport } from './routes/_private/ocupacao'
import { Route as PrivatePortariaRouteImport } from './routes/_private/portaria'
import { Route as PrivateRequestsRouteImport } from './routes/_private/requests'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PrivateManagementDepartmentsRouteImport } from './routes/_private/management/departments'
import { Route as PrivateManagementDevicesRouteImport } from './routes/_private/management/devices'
import { Route as PrivateManagementEntrancesRouteImport } from './routes/_private/management/entrances'
import { Route as PrivateManagementImportsRouteImport } from './routes/_private/management/imports'
import { Route as PrivateManagementRolesRouteImport } from './routes/_private/management/roles'
import { Route as PrivateManagementUsersRouteImport } from './routes/_private/management/users'
import { Route as PrivateManagementVehicleTypesRouteImport } from './routes/_private/management/vehicle-types'
import { Route as PrivateManagementVehiclesRouteImport } from './routes/_private/management/vehicles'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBlocksRoute = PrivateBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateHomeRoute = PrivateHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOcupacaoRoute = PrivateOcupacaoRouteImport.update({
  id: '/ocupacao',
  path: '/ocupacao',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePortariaRoute = PrivatePortariaRouteImport.update({
  id: '/portaria',
  path: '/portaria',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRequestsRoute = PrivateRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateManagementDepartmentsRoute =
  PrivateManagementDepartmentsRouteImport.update({
    id: '/management/departments',
    path: '/management/departments',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateManagementDevicesRoute =
  PrivateManagementDevicesRouteImport.update({
    id: '/management/devices',
    path: '/management/devices',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateManagementEntrancesRoute =
  PrivateManagementEntrancesRouteImport.update({
    id: '/management/entrances',
    path: '/management/entrances',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateManagementImportsRoute =
  PrivateManagementImportsRouteImport.update({
    id: '/management/imports',
    path: '/management/imports',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateManagementRolesRoute = PrivateManagementRolesRouteImport.update({
  id: '/management/roles',
  path: '/management/roles',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateManagementUsersRoute = PrivateManagementUsersRouteImport.update({
  id: '/management/users',
  path: '/management/users',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateManagementVehicleTypesRoute =
  PrivateManagementVehicleTypesRouteImport.update({
    id: '/management/vehicle-types',
    path: '/management/vehicle-types',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateManagementVehiclesRoute =
  PrivateManagementVehiclesRouteImport.update({
    id: '/management/vehicles',
    path: '/management/vehicles',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/blocks': typeof PrivateBlocksRoute
  '/home': typeof PrivateHomeRoute
  '/ocupacao': typeof PrivateOcupacaoRoute
  '/portaria': typeof PrivatePortariaRoute
  '/requests': typeof PrivateRequestsRoute
  '/management/departments': typeof PrivateManagementDepartmentsRoute
  '/management/devices': typeof PrivateManagementDevicesRoute
  '/management/entrances': typeof PrivateManagementEntrancesRoute
  '/management/imports': typeof PrivateManagementImportsRoute
  '/management/roles': typeof PrivateManagementRolesRoute
  '/management/users': typeof PrivateManagementUsersRoute
  '/management/vehicle-types': typeof PrivateManagementVehicleTypesRoute
  '/management/vehicles': typeof PrivateManagementVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/blocks': typeof PrivateBlocksRoute
  '/home': typeof PrivateHomeRoute
  '/ocupacao': typeof PrivateOcupacaoRoute
  '/portaria': typeof PrivatePortariaRoute
  '/requests': typeof PrivateRequestsRoute
  '/management/departments': typeof PrivateManagementDepartmentsRoute
  '/management/devices': typeof PrivateManagementDevicesRoute
  '/management/entrances': typeof PrivateManagementEntrancesRoute
  '/management/imports': typeof PrivateManagementImportsRoute
  '/management/roles': typeof PrivateManagementRolesRoute
  '/management/users': typeof PrivateManagementUsersRoute
  '/management/vehicle-types': typeof PrivateManagementVehicleTypesRoute
  '/management/vehicles': typeof PrivateManagementVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_private/blocks': typeof PrivateBlocksRoute
  '/_private/home': typeof PrivateHomeRoute
  '/_private/ocupacao': typeof PrivateOcupacaoRoute
  '/_private/portaria': typeof PrivatePortariaRoute
  '/_private/requests': typeof PrivateRequestsRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/management/departments': typeof PrivateManagementDepartmentsRoute
  '/_private/management/devices': typeof PrivateManagementDevicesRoute
  '/_private/management/entrances': typeof PrivateManagementEntrancesRoute
  '/_private/management/imports': typeof PrivateManagementImportsRoute
  '/_private/management/roles': typeof PrivateManagementRolesRoute
  '/_private/management/users': typeof PrivateManagementUsersRoute
  '/_private/management/vehicle-types': typeof PrivateManagementVehicleTypesRoute
  '/_private/management/vehicles': typeof PrivateManagementVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/home'
    | '/ocupacao'
    | '/portaria'
    | '/requests'
    | '/management/departments'
    | '/management/devices'
    | '/management/entrances'
    | '/management/imports'
    | '/management/roles'
    | '/management/users'
    | '/management/vehicle-types'
    | '/management/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/home'
    | '/ocupacao'
    | '/portaria'
    | '/requests'
    | '/management/departments'
    | '/management/devices'
    | '/management/entrances'
    | '/management/imports'
    | '/management/roles'
    | '/management/users'
    | '/management/vehicle-types'
    | '/management/vehicles'
  id:
    | '__root__'
    | '/_private'
    | '/_private/blocks'
    | '/_private/home'
    | '/_private/ocupacao'
    | '/_private/portaria'
    | '/_private/requests'
    | '/_public/'
    | '/_private/management/departments'
    | '/_private/management/devices'
    | '/_private/management/entrances'
    | '/_private/management/imports'
    | '/_private/management/roles'
    | '/_private/management/users'
    | '/_private/management/vehicle-types'
    | '/_private/management/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/blocks': {
      id: '/_private/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof PrivateBlocksRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/home': {
      id: '/_private/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PrivateHomeRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/ocupacao': {
      id: '/_private/ocupacao'
      path: '/ocupacao'
      fullPath: '/ocupacao'
      preLoaderRoute: typeof PrivateOcupacaoRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/portaria': {
      id: '/_private/portaria'
      path: '/portaria'
      fullPath: '/portaria'
      preLoaderRoute: typeof PrivatePortariaRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/requests': {
      id: '/_private/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof PrivateRequestsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/management/departments': {
      id: '/_private/management/departments'
      path: '/management/departments'
      fullPath: '/management/departments'
      preLoaderRoute: typeof PrivateManagementDepartmentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/devices': {
      id: '/_private/management/devices'
      path: '/management/devices'
      fullPath: '/management/devices'
      preLoaderRoute: typeof PrivateManagementDevicesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/entrances': {
      id: '/_private/management/entrances'
      path: '/management/entrances'
      fullPath: '/management/entrances'
      preLoaderRoute: typeof PrivateManagementEntrancesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/imports': {
      id: '/_private/management/imports'
      path: '/management/imports'
      fullPath: '/management/imports'
      preLoaderRoute: typeof PrivateManagementImportsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/roles': {
      id: '/_private/management/roles'
      path: '/management/roles'
      fullPath: '/management/roles'
      preLoaderRoute: typeof PrivateManagementRolesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/users': {
      id: '/_private/management/users'
      path: '/management/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof PrivateManagementUsersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/vehicle-types': {
      id: '/_private/management/vehicle-types'
      path: '/management/vehicle-types'
      fullPath: '/management/vehicle-types'
      preLoaderRoute: typeof PrivateManagementVehicleTypesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/management/vehicles': {
      id: '/_private/management/vehicles'
      path: '/management/vehicles'
      fullPath: '/management/vehicles'
      preLoaderRoute: typeof PrivateManagementVehiclesRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateBlocksRoute: typeof PrivateBlocksRoute
  PrivateHomeRoute: typeof PrivateHomeRoute
  PrivateOcupacaoRoute: typeof PrivateOcupacaoRoute
  PrivatePortariaRoute: typeof PrivatePortariaRoute
  PrivateRequestsRoute: typeof PrivateRequestsRoute
  PrivateManagementDepartmentsRoute: typeof PrivateManagementDepartmentsRoute
  PrivateManagementDevicesRoute: typeof PrivateManagementDevicesRoute
  PrivateManagementEntrancesRoute: typeof PrivateManagementEntrancesRoute
  PrivateManagementImportsRoute: typeof PrivateManagementImportsRoute
  PrivateManagementRolesRoute: typeof PrivateManagementRolesRoute
  PrivateManagementUsersRoute: typeof PrivateManagementUsersRoute
  PrivateManagementVehicleTypesRoute: typeof PrivateManagementVehicleTypesRoute
  PrivateManagementVehiclesRoute: typeof PrivateManagementVehiclesRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateBlocksRoute: PrivateBlocksRoute,
  PrivateHomeRoute: PrivateHomeRoute,
  PrivateOcupacaoRoute: PrivateOcupacaoRoute,
  PrivatePortariaRoute: PrivatePortariaRoute,
  PrivateRequestsRoute: PrivateRequestsRoute,
  PrivateManagementDepartmentsRoute: PrivateManagementDepartmentsRoute,
  PrivateManagementDevicesRoute: PrivateManagementDevicesRoute,
  PrivateManagementEntrancesRoute: PrivateManagementEntrancesRoute,
  PrivateManagementImportsRoute: PrivateManagementImportsRoute,
  PrivateManagementRolesRoute: PrivateManagementRolesRoute,
  PrivateManagementUsersRoute: PrivateManagementUsersRoute,
  PrivateManagementVehicleTypesRoute: PrivateManagementVehicleTypesRoute,
  PrivateManagementVehiclesRoute: PrivateManagementVehiclesRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
